### ISSUE TITLE
Search results showing wrong seed count

### ISSUE THREAD

**Issue by EnKrypt** [JimmyLaurent/torrent-search-api#61]
I have not looked at every provider, but for ThePirateBay at least, the seed count returned is different from the seed count actually displayed on ThePirateBay website.

As a result the results I expect to see (highest seeds first) are not what appear, since the sort also gets messed up.

**Comment by infosisio** [comment]
Yeah would be nice for this to be sorted out.

**Comment by JimmyLaurent** [comment]
You're right, the sorting seems to be messed up in the last version.

For the seed counts, I think it's different from thepiratebay.org because I used a mirror website (https://pirateproxy.id) and there may be some delay between both of them. Unfortunately, the .org is not accessible from every country.

**Comment by JimmyLaurent** [comment]
Should be fixed in 2.0.7
